spring:
    application:
        name: book-api
    datasource:
        url: jdbc:mysql://localhost:3306/bookdb
        username: root
        password: root
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL8Dialect
server:
    port: 9091